# Pipeline Configuration: PubMed Patient Case Generation

dask_workers: 8

loader:
  class: j1.data_loaders.local.LocalDataLoader
  params:
    path: results/pubmed_summaries
    format: parquet

processors:
  - class: j1.process.qa_mapper.PatientCaseMapper
    params:
      input_column: summary
      openai_model: Llama-4-Maverick-17B-128E-Instruct
      openai_base_url: http://localhost:8000/v1
      openai_api_key: x # Better to use ENV var OPENAI_API_KEY
      max_concurrent_requests: 256 # Default, can be overridden
      mcq_probability: 0.5 # 50% chance of generating multiple choice questions
      min_options: 2 # Minimum number of options for MCQ
      max_options: 6 # Maximum number of options for MCQ

output:
  path: results/pubmed_patient_case
  format: parquet
