# Pipeline Configuration: PubMed Q&A Generation

dask_workers: 8

loader:
  class: j1.data_loaders.local.LocalDataLoader
  params:
    path: results/pubmed_summaries
    format: parquet

processors:
  - class: j1.process.qa_mapper.QAPromptMapper
    params:
      input_column: summary
      openai_model: Llama-4-Maverick-17B-128E-Instruct
      openai_base_url: http://localhost:8000/v1
      openai_api_key: x # Better to use ENV var OPENAI_API_KEY
      max_concurrent_requests: 5 # Default, can be overridden
      mcq_probability: 0.5 # 50% chance of generating multiple choice questions

output:
  path: results/pubmed_qa
  format: parquet
